# Generated by Django 3.1.4 on 2021-01-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description_short', models.CharField(max_length=300)),
                ('description_long', models.TextField()),
                ('lng', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
            ],
        ),
    ]
