# Generated by Django 3.1.4 on 2021-01-02 09:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20210102_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='places',
            new_name='place',
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(),
        ),
    ]
