# Generated by Django 3.1.4 on 2021-01-02 12:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20210102_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['my_order'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Длинное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(max_length=300, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.CharField(max_length=20, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.CharField(max_length=20, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
