# Generated by Django 3.1.4 on 2021-01-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_auto_20210111_0700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='my_order',
            new_name='order',
        ),
    ]
